/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const ProductId = IDL.Nat;
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ShippingAddress = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'title' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'paymentIntent' : IDL.Text,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(OrderItem),
});
export const CreateOrderArgs = IDL.Record({
  'paymentIntent' : IDL.Text,
  'shippingAddress' : ShippingAddress,
});
export const ProductInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'inventoryCount' : IDL.Nat,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'inventoryCount' : IDL.Nat,
  'price' : IDL.Nat,
  'soldCount' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({
  'userId' : UserId,
  'items' : IDL.Vec(CartItem),
});
export const Wishlist = IDL.Record({
  'productIds' : IDL.Vec(ProductId),
  'userId' : UserId,
});
export const SortOption = IDL.Variant({
  'bestSelling' : IDL.Null,
  'newest' : IDL.Null,
  'priceDesc' : IDL.Null,
  'priceAsc' : IDL.Null,
});
export const ListProductsArgs = IDL.Record({
  'sortBy' : SortOption,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'search' : IDL.Opt(IDL.Text),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'category' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
});
export const PageResult = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Product),
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([UserId], [], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([ProductId], [], []),
  'adminListOrders' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Order)], []),
  'adminUpdateOrderStatus' : IDL.Func(
      [OrderId, OrderStatus],
      [IDL.Opt(Order)],
      [],
    ),
  'clearCart' : IDL.Func([], [], []),
  'createOrder' : IDL.Func([CreateOrderArgs], [Order], []),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], []),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getWishlist' : IDL.Func([], [Wishlist], ['query']),
  'initializeAdmin' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'listProducts' : IDL.Func([ListProductsArgs], [PageResult], ['query']),
  'removeAdmin' : IDL.Func([UserId], [], []),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'removeFromWishlist' : IDL.Func([ProductId], [], []),
  'searchProducts' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [PageResult],
      ['query'],
    ),
  'updateCartQuantity' : IDL.Func([ProductId, IDL.Nat], [], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Opt(Product)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const ProductId = IDL.Nat;
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ShippingAddress = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'title' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'paymentIntent' : IDL.Text,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(OrderItem),
  });
  const CreateOrderArgs = IDL.Record({
    'paymentIntent' : IDL.Text,
    'shippingAddress' : ShippingAddress,
  });
  const ProductInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'inventoryCount' : IDL.Nat,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'inventoryCount' : IDL.Nat,
    'price' : IDL.Nat,
    'soldCount' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const Cart = IDL.Record({ 'userId' : UserId, 'items' : IDL.Vec(CartItem) });
  const Wishlist = IDL.Record({
    'productIds' : IDL.Vec(ProductId),
    'userId' : UserId,
  });
  const SortOption = IDL.Variant({
    'bestSelling' : IDL.Null,
    'newest' : IDL.Null,
    'priceDesc' : IDL.Null,
    'priceAsc' : IDL.Null,
  });
  const ListProductsArgs = IDL.Record({
    'sortBy' : SortOption,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'search' : IDL.Opt(IDL.Text),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'category' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  const PageResult = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Product),
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([UserId], [], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([ProductId], [], []),
    'adminListOrders' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Order)], []),
    'adminUpdateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
    'clearCart' : IDL.Func([], [], []),
    'createOrder' : IDL.Func([CreateOrderArgs], [Order], []),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], []),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getWishlist' : IDL.Func([], [Wishlist], ['query']),
    'initializeAdmin' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'listProducts' : IDL.Func([ListProductsArgs], [PageResult], ['query']),
    'removeAdmin' : IDL.Func([UserId], [], []),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'removeFromWishlist' : IDL.Func([ProductId], [], []),
    'searchProducts' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'updateCartQuantity' : IDL.Func([ProductId, IDL.Nat], [], []),
    'updateProduct' : IDL.Func(
        [ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };