/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'userId' : UserId, 'items' : Array<CartItem> }
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface CreateOrderArgs {
  'paymentIntent' : string,
  'shippingAddress' : ShippingAddress,
}
export interface ListProductsArgs {
  'sortBy' : SortOption,
  'page' : bigint,
  'pageSize' : bigint,
  'search' : [] | [string],
  'maxPrice' : [] | [bigint],
  'category' : [] | [string],
  'minPrice' : [] | [bigint],
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'paymentIntent' : string,
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'title' : string,
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'delivered' : null };
export interface PageResult {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<Product>,
}
export interface Product {
  'id' : ProductId,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : string,
  'inventoryCount' : bigint,
  'price' : bigint,
  'soldCount' : bigint,
  'images' : Array<string>,
}
export type ProductId = bigint;
export interface ProductInput {
  'title' : string,
  'description' : string,
  'category' : string,
  'inventoryCount' : bigint,
  'price' : bigint,
  'images' : Array<string>,
}
export interface ShippingAddress {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'name' : string,
  'state' : string,
}
export type SortOption = { 'bestSelling' : null } |
  { 'newest' : null } |
  { 'priceDesc' : null } |
  { 'priceAsc' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface Wishlist { 'productIds' : Array<ProductId>, 'userId' : UserId }
export interface _SERVICE {
  'addAdmin' : ActorMethod<[UserId], undefined>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'addToWishlist' : ActorMethod<[ProductId], undefined>,
  'adminListOrders' : ActorMethod<[bigint, bigint], Array<Order>>,
  'adminUpdateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[CreateOrderArgs], Order>,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getCart' : ActorMethod<[], Cart>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getWishlist' : ActorMethod<[], Wishlist>,
  'initializeAdmin' : ActorMethod<[], undefined>,
  'isAdmin' : ActorMethod<[UserId], boolean>,
  'listProducts' : ActorMethod<[ListProductsArgs], PageResult>,
  'removeAdmin' : ActorMethod<[UserId], undefined>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'searchProducts' : ActorMethod<[string, bigint, bigint], PageResult>,
  'updateCartQuantity' : ActorMethod<[ProductId, bigint], undefined>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];