/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'sku' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'sellingPrice' : IDL.Nat,
  'category' : IDL.Text,
  'costPrice' : IDL.Nat,
  'reorderThreshold' : IDL.Nat,
});
export const UserId = IDL.Principal;
export const Role = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'finance' : IDL.Null,
  'sales_rep' : IDL.Null,
});
export const ActivityId = IDL.Nat;
export const ActivityType = IDL.Variant({
  'call' : IDL.Null,
  'task' : IDL.Null,
  'email' : IDL.Null,
  'meeting' : IDL.Null,
});
export const DealId = IDL.Nat;
export const ContactId = IDL.Nat;
export const Activity = IDL.Record({
  'id' : ActivityId,
  'completedAt' : IDL.Opt(Timestamp),
  'activityType' : ActivityType,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'dueDate' : Timestamp,
  'description' : IDL.Text,
  'dealId' : IDL.Opt(DealId),
  'contactId' : ContactId,
});
export const ContactStatus = IDL.Variant({
  'customer' : IDL.Null,
  'lead' : IDL.Null,
  'prospect' : IDL.Null,
});
export const Contact = IDL.Record({
  'id' : ContactId,
  'status' : ContactStatus,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const DealStage = IDL.Variant({
  'closed_won' : IDL.Null,
  'discovery' : IDL.Null,
  'prospect' : IDL.Null,
  'closed_lost' : IDL.Null,
  'proposal' : IDL.Null,
  'negotiation' : IDL.Null,
});
export const Deal = IDL.Record({
  'id' : DealId,
  'probability' : IDL.Nat,
  'closeDate' : Timestamp,
  'title' : IDL.Text,
  'value' : IDL.Nat,
  'createdAt' : Timestamp,
  'stage' : DealStage,
  'notes' : IDL.Text,
  'contactId' : ContactId,
});
export const EntityId = IDL.Nat;
export const InvoiceLineItem = IDL.Record({
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const InvoiceId = IDL.Nat;
export const InvoiceStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'paid' : IDL.Null,
  'sent' : IDL.Null,
  'overdue' : IDL.Null,
  'draft' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : InvoiceId,
  'status' : InvoiceStatus,
  'lineItems' : IDL.Vec(InvoiceLineItem),
  'dueDate' : Timestamp,
  'dealId' : IDL.Opt(EntityId),
  'invoiceNumber' : IDL.Text,
  'contactId' : EntityId,
  'issuedAt' : Timestamp,
  'paidAt' : IDL.Opt(Timestamp),
});
export const PurchaseLineItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'unitCost' : IDL.Nat,
});
export const PurchaseOrderId = IDL.Nat;
export const PurchaseOrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'submitted' : IDL.Null,
  'draft' : IDL.Null,
  'received' : IDL.Null,
});
export const PurchaseOrder = IDL.Record({
  'id' : PurchaseOrderId,
  'status' : PurchaseOrderStatus,
  'lineItems' : IDL.Vec(PurchaseLineItem),
  'createdAt' : Timestamp,
  'vendor' : IDL.Text,
  'expectedDelivery' : Timestamp,
});
export const FinancialSummary = IDL.Record({
  'grossMargin' : IDL.Nat,
  'totalExpenses' : IDL.Nat,
  'outstandingReceivables' : IDL.Nat,
  'cashBalance' : IDL.Int,
  'inventoryValue' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const UserRole = IDL.Record({ 'userId' : UserId, 'role' : Role });

export const idlService = IDL.Service({
  'adjustStock' : IDL.Func([ProductId, IDL.Int], [IDL.Opt(Product)], []),
  'assignRole' : IDL.Func([UserId, Role], [], []),
  'bootstrapFirstAdmin' : IDL.Func([], [], []),
  'completeActivity' : IDL.Func(
      [ActivityId, Timestamp],
      [IDL.Variant({ 'ok' : IDL.Opt(Activity), 'err' : IDL.Text })],
      [],
    ),
  'createActivity' : IDL.Func(
      [ActivityType, IDL.Text, ContactId, IDL.Opt(DealId), Timestamp],
      [IDL.Variant({ 'ok' : Activity, 'err' : IDL.Text })],
      [],
    ),
  'createContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ContactStatus, IDL.Text],
      [IDL.Variant({ 'ok' : Contact, 'err' : IDL.Text })],
      [],
    ),
  'createDeal' : IDL.Func(
      [IDL.Text, IDL.Nat, DealStage, ContactId, IDL.Nat, Timestamp, IDL.Text],
      [IDL.Variant({ 'ok' : Deal, 'err' : IDL.Text })],
      [],
    ),
  'createInvoice' : IDL.Func(
      [EntityId, IDL.Opt(EntityId), IDL.Vec(InvoiceLineItem), Timestamp],
      [Invoice],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [Product],
      [],
    ),
  'createPurchaseOrder' : IDL.Func(
      [IDL.Text, IDL.Vec(PurchaseLineItem), Timestamp],
      [PurchaseOrder],
      [],
    ),
  'deleteActivity' : IDL.Func(
      [ActivityId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteContact' : IDL.Func(
      [ContactId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteDeal' : IDL.Func(
      [DealId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'deleteInvoice' : IDL.Func([InvoiceId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'filterActivities' : IDL.Func(
      [IDL.Opt(ContactId), IDL.Opt(DealId)],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'filterDeals' : IDL.Func(
      [IDL.Opt(DealStage), IDL.Opt(ContactId)],
      [IDL.Vec(Deal)],
      ['query'],
    ),
  'getActivity' : IDL.Func([ActivityId], [IDL.Opt(Activity)], ['query']),
  'getContact' : IDL.Func([ContactId], [IDL.Opt(Contact)], ['query']),
  'getDeal' : IDL.Func([DealId], [IDL.Opt(Deal)], ['query']),
  'getFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
  'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getPurchaseOrder' : IDL.Func(
      [PurchaseOrderId],
      [IDL.Opt(PurchaseOrder)],
      ['query'],
    ),
  'getRevenueByPeriod' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'listActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'listDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
  'listUserRoles' : IDL.Func([], [IDL.Vec(UserRole)], ['query']),
  'removeRole' : IDL.Func([UserId], [], []),
  'searchContacts' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(ContactStatus),
      ],
      [IDL.Vec(Contact)],
      ['query'],
    ),
  'searchProducts' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Bool],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'updateContact' : IDL.Func(
      [
        ContactId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ContactStatus,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Opt(Contact), 'err' : IDL.Text })],
      [],
    ),
  'updateDeal' : IDL.Func(
      [
        DealId,
        IDL.Text,
        IDL.Nat,
        DealStage,
        ContactId,
        IDL.Nat,
        Timestamp,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : IDL.Opt(Deal), 'err' : IDL.Text })],
      [],
    ),
  'updateInvoiceStatus' : IDL.Func(
      [InvoiceId, InvoiceStatus, IDL.Opt(Timestamp)],
      [IDL.Opt(Invoice)],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Opt(Product)],
      [],
    ),
  'updatePurchaseOrderStatus' : IDL.Func(
      [PurchaseOrderId, PurchaseOrderStatus],
      [IDL.Opt(PurchaseOrder)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'sku' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'sellingPrice' : IDL.Nat,
    'category' : IDL.Text,
    'costPrice' : IDL.Nat,
    'reorderThreshold' : IDL.Nat,
  });
  const UserId = IDL.Principal;
  const Role = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'finance' : IDL.Null,
    'sales_rep' : IDL.Null,
  });
  const ActivityId = IDL.Nat;
  const ActivityType = IDL.Variant({
    'call' : IDL.Null,
    'task' : IDL.Null,
    'email' : IDL.Null,
    'meeting' : IDL.Null,
  });
  const DealId = IDL.Nat;
  const ContactId = IDL.Nat;
  const Activity = IDL.Record({
    'id' : ActivityId,
    'completedAt' : IDL.Opt(Timestamp),
    'activityType' : ActivityType,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'dueDate' : Timestamp,
    'description' : IDL.Text,
    'dealId' : IDL.Opt(DealId),
    'contactId' : ContactId,
  });
  const ContactStatus = IDL.Variant({
    'customer' : IDL.Null,
    'lead' : IDL.Null,
    'prospect' : IDL.Null,
  });
  const Contact = IDL.Record({
    'id' : ContactId,
    'status' : ContactStatus,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DealStage = IDL.Variant({
    'closed_won' : IDL.Null,
    'discovery' : IDL.Null,
    'prospect' : IDL.Null,
    'closed_lost' : IDL.Null,
    'proposal' : IDL.Null,
    'negotiation' : IDL.Null,
  });
  const Deal = IDL.Record({
    'id' : DealId,
    'probability' : IDL.Nat,
    'closeDate' : Timestamp,
    'title' : IDL.Text,
    'value' : IDL.Nat,
    'createdAt' : Timestamp,
    'stage' : DealStage,
    'notes' : IDL.Text,
    'contactId' : ContactId,
  });
  const EntityId = IDL.Nat;
  const InvoiceLineItem = IDL.Record({
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const InvoiceId = IDL.Nat;
  const InvoiceStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'paid' : IDL.Null,
    'sent' : IDL.Null,
    'overdue' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : InvoiceId,
    'status' : InvoiceStatus,
    'lineItems' : IDL.Vec(InvoiceLineItem),
    'dueDate' : Timestamp,
    'dealId' : IDL.Opt(EntityId),
    'invoiceNumber' : IDL.Text,
    'contactId' : EntityId,
    'issuedAt' : Timestamp,
    'paidAt' : IDL.Opt(Timestamp),
  });
  const PurchaseLineItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'unitCost' : IDL.Nat,
  });
  const PurchaseOrderId = IDL.Nat;
  const PurchaseOrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'submitted' : IDL.Null,
    'draft' : IDL.Null,
    'received' : IDL.Null,
  });
  const PurchaseOrder = IDL.Record({
    'id' : PurchaseOrderId,
    'status' : PurchaseOrderStatus,
    'lineItems' : IDL.Vec(PurchaseLineItem),
    'createdAt' : Timestamp,
    'vendor' : IDL.Text,
    'expectedDelivery' : Timestamp,
  });
  const FinancialSummary = IDL.Record({
    'grossMargin' : IDL.Nat,
    'totalExpenses' : IDL.Nat,
    'outstandingReceivables' : IDL.Nat,
    'cashBalance' : IDL.Int,
    'inventoryValue' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const UserRole = IDL.Record({ 'userId' : UserId, 'role' : Role });
  
  return IDL.Service({
    'adjustStock' : IDL.Func([ProductId, IDL.Int], [IDL.Opt(Product)], []),
    'assignRole' : IDL.Func([UserId, Role], [], []),
    'bootstrapFirstAdmin' : IDL.Func([], [], []),
    'completeActivity' : IDL.Func(
        [ActivityId, Timestamp],
        [IDL.Variant({ 'ok' : IDL.Opt(Activity), 'err' : IDL.Text })],
        [],
      ),
    'createActivity' : IDL.Func(
        [ActivityType, IDL.Text, ContactId, IDL.Opt(DealId), Timestamp],
        [IDL.Variant({ 'ok' : Activity, 'err' : IDL.Text })],
        [],
      ),
    'createContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ContactStatus, IDL.Text],
        [IDL.Variant({ 'ok' : Contact, 'err' : IDL.Text })],
        [],
      ),
    'createDeal' : IDL.Func(
        [IDL.Text, IDL.Nat, DealStage, ContactId, IDL.Nat, Timestamp, IDL.Text],
        [IDL.Variant({ 'ok' : Deal, 'err' : IDL.Text })],
        [],
      ),
    'createInvoice' : IDL.Func(
        [EntityId, IDL.Opt(EntityId), IDL.Vec(InvoiceLineItem), Timestamp],
        [Invoice],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [Product],
        [],
      ),
    'createPurchaseOrder' : IDL.Func(
        [IDL.Text, IDL.Vec(PurchaseLineItem), Timestamp],
        [PurchaseOrder],
        [],
      ),
    'deleteActivity' : IDL.Func(
        [ActivityId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteContact' : IDL.Func(
        [ContactId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteDeal' : IDL.Func(
        [DealId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'deleteInvoice' : IDL.Func([InvoiceId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'filterActivities' : IDL.Func(
        [IDL.Opt(ContactId), IDL.Opt(DealId)],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'filterDeals' : IDL.Func(
        [IDL.Opt(DealStage), IDL.Opt(ContactId)],
        [IDL.Vec(Deal)],
        ['query'],
      ),
    'getActivity' : IDL.Func([ActivityId], [IDL.Opt(Activity)], ['query']),
    'getContact' : IDL.Func([ContactId], [IDL.Opt(Contact)], ['query']),
    'getDeal' : IDL.Func([DealId], [IDL.Opt(Deal)], ['query']),
    'getFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
    'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getPurchaseOrder' : IDL.Func(
        [PurchaseOrderId],
        [IDL.Opt(PurchaseOrder)],
        ['query'],
      ),
    'getRevenueByPeriod' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'listActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'listDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listPurchaseOrders' : IDL.Func([], [IDL.Vec(PurchaseOrder)], ['query']),
    'listUserRoles' : IDL.Func([], [IDL.Vec(UserRole)], ['query']),
    'removeRole' : IDL.Func([UserId], [], []),
    'searchContacts' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(ContactStatus),
        ],
        [IDL.Vec(Contact)],
        ['query'],
      ),
    'searchProducts' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Bool],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'updateContact' : IDL.Func(
        [
          ContactId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ContactStatus,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Opt(Contact), 'err' : IDL.Text })],
        [],
      ),
    'updateDeal' : IDL.Func(
        [
          DealId,
          IDL.Text,
          IDL.Nat,
          DealStage,
          ContactId,
          IDL.Nat,
          Timestamp,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : IDL.Opt(Deal), 'err' : IDL.Text })],
        [],
      ),
    'updateInvoiceStatus' : IDL.Func(
        [InvoiceId, InvoiceStatus, IDL.Opt(Timestamp)],
        [IDL.Opt(Invoice)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Opt(Product)],
        [],
      ),
    'updatePurchaseOrderStatus' : IDL.Func(
        [PurchaseOrderId, PurchaseOrderStatus],
        [IDL.Opt(PurchaseOrder)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };