/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateOrderArgs {
    paymentIntent: string;
    shippingAddress: ShippingAddress;
}
export interface ProductInput {
    title: string;
    description: string;
    category: string;
    inventoryCount: bigint;
    price: bigint;
    images: Array<string>;
}
export type Timestamp = bigint;
export interface ShippingAddress {
    zip: string;
    street: string;
    country: string;
    city: string;
    name: string;
    state: string;
}
export interface OrderItem {
    title: string;
    productId: ProductId;
    quantity: bigint;
    price: bigint;
}
export interface ListProductsArgs {
    sortBy: SortOption;
    page: bigint;
    pageSize: bigint;
    search?: string;
    maxPrice?: bigint;
    category?: string;
    minPrice?: bigint;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    total: bigint;
    userId: UserId;
    createdAt: Timestamp;
    paymentIntent: string;
    shippingAddress: ShippingAddress;
    items: Array<OrderItem>;
}
export type UserId = Principal;
export interface Wishlist {
    productIds: Array<ProductId>;
    userId: UserId;
}
export interface Cart {
    userId: UserId;
    items: Array<CartItem>;
}
export type ProductId = bigint;
export interface CartItem {
    productId: ProductId;
    quantity: bigint;
}
export interface PageResult {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Product>;
}
export interface Product {
    id: ProductId;
    title: string;
    createdAt: Timestamp;
    description: string;
    category: string;
    inventoryCount: bigint;
    price: bigint;
    soldCount: bigint;
    images: Array<string>;
}
export type OrderId = bigint;
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    paid = "paid",
    delivered = "delivered"
}
export enum SortOption {
    bestSelling = "bestSelling",
    newest = "newest",
    priceDesc = "priceDesc",
    priceAsc = "priceAsc"
}
export interface backendInterface {
    addAdmin(newAdmin: UserId): Promise<void>;
    addToCart(productId: ProductId, quantity: bigint): Promise<void>;
    addToWishlist(productId: ProductId): Promise<void>;
    adminListOrders(page: bigint, pageSize: bigint): Promise<Array<Order>>;
    adminUpdateOrderStatus(id: OrderId, status: OrderStatus): Promise<Order | null>;
    clearCart(): Promise<void>;
    createOrder(args: CreateOrderArgs): Promise<Order>;
    createProduct(input: ProductInput): Promise<Product>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getCart(): Promise<Cart>;
    getMyOrders(): Promise<Array<Order>>;
    getOrder(id: OrderId): Promise<Order | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    getWishlist(): Promise<Wishlist>;
    initializeAdmin(): Promise<void>;
    isAdmin(who: UserId): Promise<boolean>;
    listProducts(args: ListProductsArgs): Promise<PageResult>;
    removeAdmin(target: UserId): Promise<void>;
    removeFromCart(productId: ProductId): Promise<void>;
    removeFromWishlist(productId: ProductId): Promise<void>;
    searchProducts(term: string, page: bigint, pageSize: bigint): Promise<PageResult>;
    updateCartQuantity(productId: ProductId, quantity: bigint): Promise<void>;
    updateProduct(id: ProductId, input: ProductInput): Promise<Product | null>;
}
import type { ListProductsArgs as _ListProductsArgs, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, Product as _Product, ShippingAddress as _ShippingAddress, SortOption as _SortOption, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdmin(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async addToCart(arg0: ProductId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async addToWishlist(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async adminListOrders(arg0: bigint, arg1: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListOrders(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListOrders(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateOrderStatus(arg0, to_candid_OrderStatus_n6(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateOrderStatus(arg0, to_candid_OrderStatus_n6(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createOrder(arg0: CreateOrderArgs): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0);
                return from_candid_Order_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0);
            return from_candid_Order_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCart(): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWishlist(): Promise<Wishlist> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async initializeAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAdmin();
            return result;
        }
    }
    async isAdmin(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async listProducts(arg0: ListProductsArgs): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_ListProductsArgs_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_ListProductsArgs_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async removeAdmin(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async removeFromCart(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async removeFromWishlist(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async searchProducts(arg0: string, arg1: bigint, arg2: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCartQuantity(arg0: ProductId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartQuantity(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductInput): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_OrderStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    total: bigint;
    userId: _UserId;
    createdAt: _Timestamp;
    paymentIntent: string;
    shippingAddress: _ShippingAddress;
    items: Array<_OrderItem>;
}): {
    id: OrderId;
    status: OrderStatus;
    total: bigint;
    userId: UserId;
    createdAt: Timestamp;
    paymentIntent: string;
    shippingAddress: ShippingAddress;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n4(_uploadFile, _downloadFile, value.status),
        total: value.total,
        userId: value.userId,
        createdAt: value.createdAt,
        paymentIntent: value.paymentIntent,
        shippingAddress: value.shippingAddress,
        items: value.items
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} | {
    delivered: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "paid" in value ? OrderStatus.paid : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ListProductsArgs_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListProductsArgs): _ListProductsArgs {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_SortOption_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOption): _SortOption {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sortBy: SortOption;
    page: bigint;
    pageSize: bigint;
    search?: string;
    maxPrice?: bigint;
    category?: string;
    minPrice?: bigint;
}): {
    sortBy: _SortOption;
    page: bigint;
    pageSize: bigint;
    search: [] | [string];
    maxPrice: [] | [bigint];
    category: [] | [string];
    minPrice: [] | [bigint];
} {
    return {
        sortBy: to_candid_SortOption_n12(_uploadFile, _downloadFile, value.sortBy),
        page: value.page,
        pageSize: value.pageSize,
        search: value.search ? candid_some(value.search) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortOption): {
    bestSelling: null;
} | {
    newest: null;
} | {
    priceDesc: null;
} | {
    priceAsc: null;
} {
    return value == SortOption.bestSelling ? {
        bestSelling: null
    } : value == SortOption.newest ? {
        newest: null
    } : value == SortOption.priceDesc ? {
        priceDesc: null
    } : value == SortOption.priceAsc ? {
        priceAsc: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} | {
    delivered: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.paid ? {
        paid: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
